### PR TITLE
Edited cubicvr/source/Texture.cpp via GitHub

### PR DESCRIPTION
**Pull request by PH3NIX**
Added support for direct loading of the Sega Dreamcast PVR (VQ) Compression.

I go by PH3NOM, but that name was already taken here on github :-(

### CODE REVIEW

**Comment by PH3NIX** [comment]
loadpvr:
I have written this function from scratch. It is updated from information posted here: 
http://www.fabiensanglard.net/Mykaruga/tools/segaPVRFormat.txt

To encode pvr-vq textures, I have updated the encoder vqenc to add a standard pvr file header.
http://www.megaupload.com/?d=UL7QOSAZ

**Comment by cjcliffe** [comment]
Looks great, merged -- do you mind if I include your modified VQENC source as a tool in the cubicvr repository as well?  Should get that up on a GitHub project as well :)

**Comment by PH3NIX** [comment]
Sound good.  I think it is a good idea to post the tool also.

If there is anything else I can help with on the Dreamcast side of things, let me know!

How far are we from seeing .bsp loading on DC?

**Comment by cjcliffe** [comment]
BSP should technically load now, it just currently lacks support for loading JPEGs and secondary lightmap blending so it would render all black.   I'm using tinyjpeg now so it should be possible to upload the textures it will just be a matter of memory limits.

**Pull request merged**
